import * as React from 'react'
import { useState } from 'react'
import Head from 'next/head'

import { ThemeProvider } from 'styled-components'

import dark from '../src/styles/themes/dark'
import light from '../src/styles/themes/light'

import GlobalStyles from '../src/styles/global'
import { Container } from './style'
import { Header } from '../components/Header'
import { Main } from '../components/Main'
import { Nav } from '../components/Nav'

export default function Home() {
  const [theme, setTheme] = useState(dark)

  function toggleTheme() {
    setTheme(theme === dark ? light : dark)
  }

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Junio KOI - Portfolio</title>
        <link
          rel="shortcut icon"
          href={'assets/favicon.png'}
          type="image/x-icon"
        />
      </Head>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=JetBrains+Mono:wght@400;700&family=Source+Sans+Pro:wght@400;700&display=swap"
        rel="stylesheet"
      />

      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <Container>
          <Header toggleTheme={toggleTheme} />
          <Main />
          <Nav />
        </Container>
      </ThemeProvider>
    </div>
  )
}
